<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_www.npru.ac.thNPRU</name>
   <tag></tag>
   <elementGuidId>5d33a74b-a325-40d7-ab47-98afa3c6048d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.d-ib.fz-20.lh-26.td-hu.tc.va-bot.mxw-100p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1e262ef7-a265-48de-b93c-02e8213feecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>10f1e0a2-728f-478b-b064-9e98e28a3291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>18a94554-0766-45ed-92ec-bc79ff1d738b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>74fc238d-854b-463c-8ccf-3251a085253d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>6acda768-19af-4b82-addc-1a789ee75431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.npru.ac.th/</value>
      <webElementGuid>226d0ad9-5b29-4ea7-8c77-bf997b9c7a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-45c</name>
      <type>Main</type>
      <value>60f0b71a5fcd00</value>
      <webElementGuid>6f283e70-92cb-4b42-be0b-15b1e216631d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NPRU</value>
      <webElementGuid>d90cabc0-baaa-4561-a64c-ed48c8d6456a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.npru.ac.thNPRU</value>
      <webElementGuid>bcde3ed6-c1ba-4d51-93a6-a2c6df49020d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg  searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd fst algo algo-sr relsrch richAlgo&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>33b685e8-1d3d-4b31-b69f-bbaf2cc6fab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>26f67777-19f1-42b9-b095-a031e8d95bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.npru.ac.th/')]</value>
      <webElementGuid>da8f4f8f-8978-4557-9be1-a2f48a8f7a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>03d2cfc7-3c6f-4e28-b366-fb5c420f1c48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.npru.ac.th/' and (text() = 'www.npru.ac.thNPRU' or . = 'www.npru.ac.thNPRU')]</value>
      <webElementGuid>e035b38d-8645-4aee-80b8-0ef57cd5d9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
