<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_www.npru.ac.thNPRU</name>
   <tag></tag>
   <elementGuidId>06424765-0ed4-4986-8086-9879d1ba2da7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>63a151a0-74d4-46f8-aeef-58e0e85ee2ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p</value>
      <webElementGuid>e80b5834-4287-4179-b300-800a89617113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-matarget</name>
      <type>Main</type>
      <value>algo</value>
      <webElementGuid>e45e3ea8-a573-4ec9-ba52-bcbe71d27c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.npru.ac.th/</value>
      <webElementGuid>33116a42-94a0-4d96-b6ff-913e8d2debd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>ac8157bb-ea5b-4c81-9798-365174a30e8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>aec420ec-e8cc-4c99-acb3-72ccf0848a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-7b4</name>
      <type>Main</type>
      <value>65a631adccd3f</value>
      <webElementGuid>29596a82-a68b-41e7-80e3-8cd2414d88b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>NPRU</value>
      <webElementGuid>3ccd1606-ba26-4610-88ce-5bbb50795eec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>www.npru.ac.thNPRU</value>
      <webElementGuid>584950ba-c27a-4d97-9603-8ccafda2a3e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;web&quot;)/ol[@class=&quot;reg searchCenterMiddle&quot;]/li[@class=&quot;first&quot;]/div[@class=&quot;dd algo algo-sr relsrch fst richAlgo&quot;]/div[@class=&quot;compTitle options-toggle&quot;]/h3[@class=&quot;title&quot;]/a[@class=&quot;d-ib fz-20 lh-26 td-hu tc va-bot mxw-100p&quot;]</value>
      <webElementGuid>be1868eb-a921-46ae-9418-703579048955</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='web']/ol/li/div/div/h3/a</value>
      <webElementGuid>fd720fe0-1d1a-49ec-bdba-b58747dce011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.npru.ac.th/')]</value>
      <webElementGuid>867bf129-6476-4332-be47-b6fbec3c40e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3/a</value>
      <webElementGuid>9cbf440e-158b-43d6-b17a-16313e9f4e31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.npru.ac.th/' and (text() = 'www.npru.ac.thNPRU' or . = 'www.npru.ac.thNPRU')]</value>
      <webElementGuid>0d5266f4-fa16-4345-87a5-af368af0baf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
